  version: 0.0
  os: linux
  files:
    - source: .
      destination: /home/ec2-user/sample-java-project/
  commands:
    - echo "set_permissions"
    - cd /home/ec2-user/sample-java-project/scripts
    - sudo chmod +x start_server.sh
    - sudo chmod +x install_dependencies.sh
    
  hooks:
    AfterInstall:
      - location: scripts/install_dependencies.sh
        timeout: 300
        runas: ec2-user
    ApplicationStart:
      - location: scripts/start_server.sh
        timeout: 300
        runas: ec2-user